### ISSUE TITLE
Incorrect Explanation of Specificity

### ISSUE THREAD

**Issue by ethanwright3** [EducationShinyAppTeam/Bayes_Theorem#1]
I am fairly confident Specificity is defined wrong. The pop up describes it as, “the probability of someone who does not have the disease testing positive for it”. However, that would mean slider default of .99 would be .99 probability that there would be .99 false positive chance. I believe it should be, "the probability of someone who does not have the disease testing negative for it."

**Comment by neilhatfield** [comment]
Fixed.
